theme: jekyll-theme-cayman
title: Jenny A. Fisher
description: Centre for Atmospheric Chemistry, University of Wollongong

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Teaching:
    - Teaching Portfolio: "https://sites.google.com/view/jfisher-teaching-portfolio/home"
    - Jupyter Notebooks: "https://jennyfisher.github.io/computing-modelling-earthsci/"
